615 fuji runner external file
cessda/cessda.cdc.fuji.runner pull request #29
Opened 2023-12-07 14:44 UTC by kpapag

change-log

- Added support for assessment using FAIR EVA app
- Added support for file logging system
- Added support for timeout - retry for all API Calls
- Added support for file input of one or more sitemaps to assess
- Added support for file input of one or more studies (same or different SP) to assess
- Added support for assessing studies of CDC Staging Env (currently only F-UJI API)
- Added support for saving failed studies to a file and re-assess them before script ends
- Added support for inputting Service Provider sitemaps beside CESSDA (previous version only run on CDC sitemap by default)
- Added (studyNumber, Publisher) to CSV for scores comparison, obtained by CDC Internal AP

2024-01-09 10:05 UTC, matthew-morris-cessda requested changes
I've reviewed the changed code and left some comments and suggested changes

2024-01-09 10:05 UTC, matthew-morris-cessda commented on src/sitemaps.ts
> +await isFileEmpty('../outputs/failed.txt')
`../outputs/failed.txt` is removed at line 16, so this will never work as intended

2024-01-09 10:05 UTC, matthew-morris-cessda commented on src/types/global.d.ts
It would be better to simply export `StudyInfo` directly rather than using the global namespace

2024-01-23 14:49 UTC, matthew-morris-cessda approved these changes

2024-01-23 14:50 UTC, matthew-morris-cessda commented
@john-shepherdson Could you take a look?

2024-01-23 14:55 UTC, john-shepherdson approved these changes

2024-01-23 14:55 UTC, merged